import React, { useState } from 'react'
import Head from 'next/head'
import Layout from '../components/layout/Layout'
import Sidebar from '../components/layout/Sidebar'
import ParallaxMob from '../components/parallax/ParallaxMob'
import ParallaxDesktop from '../components/parallax/ParallaxDesktop'
import { parallaxData } from '../interfaces/interfaces'

const Home = ({ isMobile }): JSX.Element => {
  const [parallaxLayer, setParalaxLayer] = useState<parallaxData>(0)

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <Sidebar
          display={!isMobile ? 'flex' : 'none'}
          setParalaxLayer={setParalaxLayer}
          sideBarScrollPosition={parallaxLayer}
        />
        {isMobile ? (
          <ParallaxMob isMobile={isMobile} />
        ) : (
          <ParallaxDesktop
            isMobile={isMobile}
            sideBarScrollPosition={parallaxLayer}
            setParalaxLayer={setParalaxLayer}
          />
        )}
      </Layout>
    </>
  )
}

export default Home

export async function getServerSideProps(ctx: any) {
  const UA = ctx.req.headers['user-agent']
  const isMobile = Boolean(
    UA.match(/Android|BlackBerry|iPhone|iPad|iPod|Opera Mini|IEMobile|WPDesktop/i),
  )

  return {
    props: {
      isMobile,
    },
  }
}
